apiVersion: v1
kind: Service
metadata:
  name: car-db
spec:
  ports:
    - port: 3306
  selector:
    app: car-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-db-deployment
spec:
  selector:
    matchLabels:
      app: car-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: car-db
    spec:
      hostname: car-db
      containers:
        - image: mysql:8.0.22
          name: car-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test
            - name: MYSQL_DATABASE
              value: car_db
          ports:
            - containerPort: 3306
              name: car-db
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: carshop-web-app
  name: carshop-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carshop-web-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: carshop-web-app
    spec:
      containers:
        - image: azormpas/spring-boot-app:1.0.9
          name: carshop-web-app
          ports:
            - containerPort: 8080
              name: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: carshop-web-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
